### ISSUE TITLE
Mana burst is invisible after warping

### ISSUE THREAD

**Issue by Liath0524** [VazkiiMods/Botania#3636]
# Version Information
Forge version:  1.16.4-35.1.37
Botania version:  1.16.4-411

# Further Information
Steps to reproduce:
![2021-02-02_17 02 57](https://user-images.githubusercontent.com/78397950/106550744-a09c2280-6578-11eb-9e60-7db5d279f7f9.png)
Set up as in image, with pulse mana spreader (warp lens) aimed at force relay, force relay linked to block above stone block, and hourglass set to 1 second.

What I expected to happen:
The mana burst would teleport to above the stone block and continue until it strikes the mana pool. This occurs as expected when using a bore-warp lens instead: 
![2021-02-02_17 03 07](https://user-images.githubusercontent.com/78397950/106550763-a7c33080-6578-11eb-8526-d3ee3eb8dc85.png)

What happened instead:
The mana burst strikes the relay and seems to disappear. However the burst still exists as the mana detector still activates, as seen in first image.

**Comment by teeth-eator** [comment]
I can confirm that this happens to me too, fairly consistently. Also the mana burst seems to not carry any mana after warping, so it's unable to fill pools or perform any other function after passing through a prism

**Comment by Hubry** [comment]
> Also the mana burst seems to not carry any mana after warping
Fully intended, no teleporting ~~bread~~ mana.

**Comment by teeth-eator** [comment]
Well, you could teleport mana with bore-warping lenses anyways, and doing it without the bore is actually significantly more complicated because the spreader doesn't automatically fire into the relay, so I don't see why you shouldn't be able to teleport mana like that

**Comment by williewillus** [comment]
i think this is just an artifact of vanilla's client-server syncing being weird

you can observe it also by firing a blaster and noting how the stream of particles "disconnects" a couple seconds in, when the server corrects the client about the burst's path

Needs more investigating around how vanilla sync works here and if we can do anything about it. Wonder if it's worth introducing a base-rendered sprite for the burst instead of relying on particles alone like it does now.
