### ISSUE TITLE
Incompativility with HungTeen's Plants vs Zombies

### ISSUE THREAD

**Issue by aburone** [VazkiiMods/Botania#3814]
java.lang.IllegalArgumentException: Can't find attribute botania:pixie_spawn_chance

# Version Information
Forge version:  36.2..4
Botania version:  Botania-1.16.5-419.jar

# Further Information
Link to crash log: https://hastebin.com/jiredecema.rb

Steps to reproduce
This gets triggered when some pvz mob trows some yellow ball at me.
I believe those are the giant's but can't be sure because the crash happens too fast

The game crashes

**Comment by aburone** [comment]
Well. It not only with PvZ.
Anything that flies seems to be affected. On this case: arrows
https://hastebin.com/itexeqeven.rb

Any config option I can change to prevent pixies trying to spawn?

**Comment by Hubry** [comment]
There is no config option, and it almost certainly is caused by a mod doing something really dumb with attribute registration for player entities.
* Add `-Dmixin.debug.export=true` to Java arguments
* Run the game
* Open the game directory, navigate through `.mixin.out/class/net/minecraft/entity/player/`, make a zip archive with `PlayerEntity.class` and post it here.

**Comment by Hubry** [comment]
Nevermind, I think I found it. Try without GT4 Reimagined.
<https://github.com/Trinsdar/GT-4-Reimagined/blob/c89641b99f4c5a32b104e4b27e2114f762075869/src/main/java/trinsdar/gt4r/mixin/PlayerEntityMixin.java#L40>
